### ISSUE TITLE
有点云窗口，但无实际点云输出

### ISSUE THREAD

**Issue by leyuan-sun** [wylnii/ORBSLAM2_with_pointcloud_map#1]
你好
我跑个别的dataset，有轨迹窗口，点云窗口，但是点云窗口无点云输出，终端显示也有点云生成，这是为什么？

**Comment by leyuan-sun** [comment]
Start processing sequence ...
Images in the sequence: 1074

New map created with 815 points
Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.1.34185e+09 receive a keyframe, id = 1
generate point cloud for kf 0, size=0
show global map, size=0
1.34185e+09 receive a keyframe, id = 2
show global map, size=0
1.34185e+09 receive a keyframe, id = 3
generate point cloud for kf 1, size=21024
generate point cloud for kf 0, size=0
generate point cloud for kf 2, size=21108

**Comment by wylnii** [comment]
hi，你好，感谢你关注我的github。

这个项目现在已不在更新，所以我也有些记不清了，我大概记得当时测试时好像是有的dataset是没办法跑的（主要是因为场景变化过快导致特征匹配失败，中间跟踪断掉了），你可以确认一下轨迹窗口是不是也停止更新了，如果是的话可能就是这个问题。

另外，这个代码我也是在别人基础上粗糙的改了一下，还有许多需要完善的地方，由于我现在工作已经和此不相关了，所以没办法帮你debug（主要是快忘完了😂），非常抱歉。

如有其他问题欢迎提问，我会尽力帮你解答。

**Comment by wylnii** [comment]
> 你好
> 我跑个别的dataset，有轨迹窗口，点云窗口，但是点云窗口无点云输出，终端显示也有点云生成，这是为什么？

hi，你好，感谢你关注我的github。

这个项目现在已不在更新，所以我也有些记不清了，我大概记得当时测试时好像是有的dataset是没办法跑的（主要是因为场景变化过快导致特征匹配失败，中间跟踪断掉了），你可以确认一下轨迹窗口是不是也停止更新了，如果是的话可能就是这个问题。

另外，这个代码我也是在别人基础上粗糙的改了一下，还有许多需要完善的地方，由于我现在工作已经和此不相关了，所以没办法帮你debug（主要是快忘完了😂），非常抱歉。

如有其他问题欢迎提问，我会尽力帮你解答。

**Comment by leyuan-sun** [comment]
> > 你好
> > 我跑个别的dataset，有轨迹窗口，点云窗口，但是点云窗口无点云输出，终端显示也有点云生成，这是为什么？
> 
> hi，你好，感谢你关注我的github。
> 
> 这个项目现在已不在更新，所以我也有些记不清了，我大概记得当时测试时好像是有的dataset是没办法跑的（主要是因为场景变化过快导致特征匹配失败，中间跟踪断掉了），你可以确认一下轨迹窗口是不是也停止更新了，如果是的话可能就是这个问题。
> 
> 另外，这个代码我也是在别人基础上粗糙的改了一下，还有许多需要完善的地方，由于我现在工作已经和此不相关了，所以没办法帮你debug（主要是快忘完了），非常抱歉。
> 
> 如有其他问题欢迎提问，我会尽力帮你解答。

谢谢回答 不是因为TRACK LOST掉了的原因，轨迹一直有的。
